

#         Powered by TabooLib 6.1         #


# 星级配置
star:
  # 槽位未镶嵌宝石时的样子
  empty: "〇"
  # 槽位镶嵌宝石后
  fill: "۞"
  # 颜色配置
  color:
    # 如果槽位数量显示的颜色没有配置则显示 0 所对应的颜色
    # 可以解析 &{#00FFFF}
    0: "&e"
    1: "&e"
    2: "&e"
    3: "&a"
    4: "&a"
    5: "&1"
    6: "&1"
    7: "&5"
    8: "&5"
    9: "&6"
    10: "&6"

# 鉴定配置
jd:
  # 玩家鉴定出多少星级及以上时全服通告
  # TODO: Kether
  tipLevel: 5
  # 鉴定成功出的星级,概率
  levels:
    1: 485
    2: 700
    3: 500
    4: 180
    5: 85
    6: 35
    7: 15
    8: 4

# 打孔配置
dig:
  # 打孔成功出多少及以上星级时全服提示
  # TODO: Kether
  tipLevel: 5
  # 当前星级 打孔成功率 (提示:无法超过装备本身的限制)
  levels:
    1: 90
    2: 50
    3: 33
    4: 25
    5: 20
    6: 16
    7: 14

# 这个功能我没看懂, 忘记当初为什么会做这个东西了
# 暂时先留着
smith:
  need: 5

# items 被我扔到新的配置文件了